id = "mypy"
name = "mypy"
version = "0.0.1"
schema_version = 1
authors = ["Antoine Montes <antoine.montes@epita.fr>"]
description = "Mypy extension for Zed"
repository = "https://github.com/Zenor27/zed-mypy"

[language_servers.mypy]
name = "Mypy"
languages = ["Python"]
